# Minimal analysis configuration - suppress all non-critical issues
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Disable all lint rules for cleaner output
    avoid_print: false
    avoid_types_as_parameter_names: false
    empty_catches: false
    prefer_const_constructors: false
    curly_braces_in_flow_control_structures: false
    unnecessary_brace_in_string_interps: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
    - "build/**"
  
  errors:
    # Ignore all non-critical issues
    unused_element: ignore
    unused_field: ignore
    unused_local_variable: ignore
    unused_import: ignore
    dead_code: ignore
    use_build_context_synchronously: ignore
    deprecated_member_use: ignore
    todo: ignore
    must_be_immutable: ignore
    always_declare_return_types: ignore
    always_require_non_null_named_parameters: ignore
    always_specify_types: ignore
    avoid_empty_else: ignore
    avoid_relative_lib_imports: ignore
    avoid_returning_null_for_future: ignore
    avoid_shadowing_type_parameters: ignore
    avoid_slow_async_io: ignore
    avoid_unnecessary_containers: ignore
    cancel_subscriptions: ignore
    close_sinks: ignore
    comment_references: ignore
    control_flow_in_finally: ignore
    directives_ordering: ignore
    hash_and_equals: ignore
    implementation_imports: ignore
    invariant_booleans: ignore
    iterable_contains_unrelated_type: ignore
    list_remove_unrelated_type: ignore
    literal_only_boolean_expressions: ignore
    no_adjacent_strings_in_list: ignore
    no_duplicate_case_values: ignore
    only_throw_errors: ignore
    prefer_adjacent_string_concatenation: ignore
    prefer_collection_literals: ignore
    prefer_conditional_assignment: ignore
    prefer_const_declarations: ignore
    prefer_final_fields: ignore
    prefer_final_in_for_each: ignore
    prefer_final_locals: ignore
    prefer_for_elements_to_map_fromIterable: ignore
    prefer_function_declarations_over_variables: ignore
    prefer_if_null_operators: ignore
    prefer_initializing_formals: ignore
    prefer_interpolation_to_compose_strings: ignore
    prefer_is_empty: ignore
    prefer_is_not_empty: ignore
    prefer_is_not_operator: ignore
    prefer_iterable_whereType: ignore
    prefer_null_aware_operators: ignore
    prefer_single_quotes: ignore
    prefer_spread_collections: ignore
    prefer_typing_uninitialized_variables: ignore
    recursive_getters: ignore
    sized_box_for_whitespace: ignore
    sort_child_properties_last: ignore
    sort_constructors_first: ignore
    sort_pub_dependencies: ignore
    sort_unnamed_constructors_first: ignore
    test_types_in_equals: ignore
    throw_in_finally: ignore
    unawaited_futures: ignore
    unnecessary_await_in_return: ignore
    unnecessary_brace_in_string_interps: ignore
    unnecessary_const: ignore
    unnecessary_getters_setters: ignore
    unnecessary_lambdas: ignore
    unnecessary_new: ignore
    unnecessary_null_aware_assignments: ignore
    unnecessary_null_in_if_null_operators: ignore
    unnecessary_overrides: ignore
    unnecessary_parenthesis: ignore
    unnecessary_raw_strings: ignore
    unnecessary_statements: ignore
    unnecessary_string_escapes: ignore
    unnecessary_string_interpolations: ignore
    unnecessary_this: ignore
    unrelated_type_equality_checks: ignore
    unsafe_html: ignore
    use_full_hex_values_for_flutter_colors: ignore
    use_key_in_widget_constructors: ignore
    use_rethrow_when_possible: ignore
    use_string_buffers: ignore
    use_to_and_as_if_applicable: ignore
    valid_regexps: ignore
