// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_FIREBASE_WEB_API_KEY_HERE',
    appId: 'YOUR_FIREBASE_WEB_APP_ID_HERE',
    messagingSenderId: 'YOUR_FIREBASE_MESSAGING_SENDER_ID_HERE',
    projectId: 'YOUR_FIREBASE_PROJECT_ID_HERE',
    authDomain: 'YOUR_FIREBASE_AUTH_DOMAIN_HERE',
    storageBucket: 'YOUR_FIREBASE_STORAGE_BUCKET_HERE',
    measurementId: 'YOUR_FIREBASE_MEASUREMENT_ID_HERE',
    databaseURL: 'YOUR_FIREBASE_DATABASE_URL_HERE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPwqX7mpf757PbTYn29dy8tw510XFuhF0',
    appId: '1:868343457049:android:771373959459a135831188',
    messagingSenderId: '868343457049',
    projectId: 'calorie-vita',
    storageBucket: 'calorie-vita.firebasestorage.app',
  );
} 